SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE airline;
TRUNCATE TABLE airport;
TRUNCATE TABLE route;
TRUNCATE TABLE flight;
TRUNCATE TABLE role;
TRUNCATE TABLE user;
TRUNCATE TABLE ticket;
SET FOREIGN_KEY_CHECKS = 1;
